config/routes.rb
Rails.application.routes.draw do
  resources :home, only: :index
  resources :groups, only: [:index, :new, :create],path: 'categories' do
    resources :expenses, only: [:index, :new, :create] 
  end
  devise_for :users

  # Add the following route for signing out
  resources :users, only: [:show]

   root "home#index"
end

app/models/ability.rb
class Ability
  included CanCan::Ability

  def initialize(user)
    user ||= User.new

    return unless user.present?

    can(:read, MyGroups, author_id: user.id)
    can(:read, Expense, author_id: user.id)
    can(:read, User, id: user.id)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :expense_groups, class_name: 'ExpenseGroup', foreign_key: 'group_id', dependent: :destroy
  has_many :my_groups, through: :expense_groups

  accepts_nested_attributes_for :expense_groups

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :author_id, presence: true
end

app/models/expense_group.rb
class ExpenseGroup < ApplicationRecord
  belongs_to :my_groups, class_name: 'MyGroup', foreign_key: 'group_id'
  belongs_to :expense, class_name: 'Expense', foreign_key: 'expense_id'

  validates :group_id, presence: true
  validates :expense_id, presence: true
end

app/models/my_group.rb
class MyGroup < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :expense_groups, class_name: 'ExpenseGroup', foreign_key: 'group_id', dependent: :destroy
  has_many :expenses, through: :expense_groups

  accepts_nested_attributes_for :expense_groups

  validates :name, presence: true
  validates :icon, presence: true
  validates :author_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expenses, class_name: 'Expense', foreign_key: 'author_id'
  has_many :my_groups, class_name: 'MyGroup', foreign_key: 'author_id'

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/expense_groups_controller.rb
class ExpenseGroupsController < ApplicationController
  def index; end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @user = current_user
    @group = MyGroup.find(params[:group_id])
    @expenses = @group.expenses.order(created_at: :desc)
    @expenses_sum = @expenses.sum(:amount) || 0
  end

  def new
    @user = current_user
    @group = MyGroup.find(params[:group_id])
    @categories = @user.my_groups
    @expense = Expense.new
  end

  def create
    @user = current_user
    @group = MyGroup.find(params[:group_id])
    category_ids = params[:expense][:category_ids]

    if category_ids.present?

      @expense = Expense.new(expense_params.except(:category_ids))
      @expense.author = @user
      if @expense.save
        category_ids.each do |category_id|
          ExpenseGroup.create(group_id: category_id.to_i, expense_id: @expense.id)
        end
        redirect_to group_expenses_path(@group)

      else
        redirect_to new_group_expense_path(@group, notice: 'Failed to create expense')

      end
    else

      redirect_to new_group_expense_path(@group, notice: 'Please select at least one category')

    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!
  def index
    @user = current_user
    @groups = @user.my_groups
  end

  def new
    @group = MyGroup.new
  end

  def create
    @group = MyGroup.new(group_params.except(:icon))
    @group.author = current_user
    uploaded_icon = params[:my_group][:icon]
    if uploaded_icon.present?
      file_path = Rails.root.join('app', 'assets', 'images', uploaded_icon.original_filename)
      File.binwrite(file_path, uploaded_icon.read)
      @group.icon = uploaded_icon.original_filename
    end
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:my_group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return unless user_signed_in?

    redirect_to groups_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show
    if params[:id] == 'sign_out'
      sign_out(current_user)
      redirect_to root_path, notice: 'You have been signed out successfully.'
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/index.html.erb
<%= render partial: 'shared/header',locals: {left:'back', path:root_path ,middle: 'EXPENSES $'+ number_with_precision(@expenses_sum, precision: 2).to_s }%>
<%= render partial: 'shared/notice' %>
<div class='main-content'>
<% if @expenses.empty? %>

<h1 class='heading blue-text'> No Expense was made </h1>

<%else%>
<h1 class='heading blue-text' > List of expenses </h1>
<% @expenses.each do |expense| %>
<div class = 'expense-card'> 
<p> <strong>Expense : </strong> <%=expense.name%> </p>
<p><strong> Date : </strong> <%=expense.created_at.strftime('%d %b %Y')%> </p>
<p> <strong>TOTAL PAYEMENT </strong>    $<%=number_with_precision(expense.amount, precision: 2)%> </p>
</div>

<% end %>

<%end%>
</div>

 <div class='footer-button'>
<%= link_to "ADD EXPENSE", new_group_expense_path(@group), method: :get, class: "btn ", id:'add-expense' %>
</div>

app/views/expenses/new.html.erb
<%= render partial: 'shared/header', locals: {left:'back', path:group_expenses_path(@group) , middle: 'NEW EXPENSE'}%>
<%= render partial: 'shared/notice' %>
<% if params[:notice].present? %>
  <div class="notice">
    <%= params[:notice] %>
  </div>
<% end %>

<%= form_with(model: @expense, url: group_expenses_path(@group), method: :post ) do |f| %>

<div class="form-container">
 <div class="field">
    <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Name", class:'form-control' %>
  </div>

   <div class="field">
  <%= f.number_field :amount, autofocus: true, autocomplete: "off", step:'0.01',min:'0.01', placeholder: "Amount", class:'form-control' %>
  </div>
        <h3> select the categories of this expense </h3>
  <div class="field categories-check">
    <% @categories.each do |category| %>
    <div>
      <%= f.check_box :category_ids, { multiple: true }, category.id, nil %>
      <%= category.name %><br>
     </div>
    <% end %>
  </div>

 <%= f.submit 'Save', class: 'btn btn-primary save_button'  %>

</div>

<%end%>

app/views/groups/index.html.erb
<%= render partial: 'shared/header', locals: {left:'hamburger' , middle: 'CATEGORIES'}%>
<%= render partial: 'shared/notice' %>

<div class='main-content'>
  <% if @groups.any? %>
  <h1 class = 'heading blue-text'> List of Categories of <%=@user.name%> </h1>
    <% @groups.each do |group| %>
      <%= link_to group_expenses_path(group),class:'category-card' do %>
       
          <div class='icon-container'>
            <% if group.icon.present? %>
              <%= image_tag group.icon %>
            <% end %>
          </div>
          <div class='group-information'>
            <p><%= group.name %></p>
            <p><%= group.created_at.strftime('%d %b %Y') %></p>
          </div>
          <div class='group-amount'> $<%=number_with_precision(group.expenses.sum(:amount), precision: 2) || 0.00 %> </div>
   
      <% end %>
    <% end %>
  <% else %>
    <h1 class='heading blue-text'>No category exists</h1>
  <% end %>
</div>
   <div class='footer-button'>
  <%= link_to "ADD CATEGORY", new_group_path, method: :get, class: "btn", id:'add-category' %>
  </div>

app/views/groups/new.html.erb
<%= render partial: 'shared/header', locals: {left:'back', path:root_path, middle: 'NEW CATEGORY'}%>
<%= render partial: 'shared/notice' %>

<%= form_with(model: @group, url: groups_path, method: :post ) do |f| %>

<div class="form-container">
 <div class="field">
    <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Name", class:'form-control' %>
  </div>

   <div class="field">
  <label for="icon">ICON </label>
  <%= f.file_field :icon, autofocus: true, autocomplete: "off", placeholder: "Icons", class:'form-control' %>
  </div>

 <%= f.submit 'Save', class: 'btn btn-primary save_button'  %>

</div>

<%end%>

app/views/home/index.html.erb
<div class='splash-screen'>
  <h1 class= 'splash-title'> Budget Expenses app </h1>
<div class= 'links_buttons'>
  <%= button_to "LOG IN", new_user_session_path, method: :get, class: 'btn btn-primary link_button' %>
  <%= button_to "SIGN UP", new_user_registration_path, method: :get, class: 'btn btn-primary link_button'%>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>

    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_header.html.erb
<div class = 'header'> 
<% if left == 'hamburger'%>
<nav id="hamburger-button">
      <div class="bar1"></div>
    <div class="bar2"></div>
    <div class="bar3"></div>
    </nav>

    <%end%>
<% if left == 'back' %>
<%= link_to path do%>
<%= image_tag('arrow-118-32.png', class:'icon') %>
<%end%>
<%end%>


<h2> <%= middle %> </h2>

<%=link_to user_path(id:'sign_out') do%>
<%= image_tag('icons8-logout-64.png',class:'icon')%>
<%end%>

</div>

app/views/shared/_notice.html.erb
<div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>